// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Jason Huang and cfl3d-cpp contributors.
// Part of cfl3d-cpp (https://github.com/JasonHuang330/cfl3d-cpp).
// Licensed under the Apache License, Version 2.0 (see the LICENSE file).
// common_blocks.h — auto-generated by f2cpp common_mapper.
// One struct per Fortran COMMON block: defined once,
// included everywhere. DO NOT EDIT BY HAND.
#pragma once
#include <complex>
#include <cstddef>
#include <cstdint>

// COMMON /account/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonAccount {
    int32_t iaccnt;
    int32_t ioutsub;
};
extern CommonAccount cmn_account;

// COMMON /alloc/ — unique, 6 declaration site(s) in 1 file(s)
struct CommonAlloc {
    int32_t iptr;
    int32_t imax;
    int32_t ifptr;
    int32_t ifmax;
};
extern CommonAlloc cmn_alloc;

// COMMON /alphait/ — unique, 7 declaration site(s) in 7 file(s)
struct CommonAlphait {
    int32_t ialphit;
    float cltarg;
    float rlxalph;
    float dalim;
    float dalpha;
    int32_t icycupdt;
};
extern CommonAlphait cmn_alphait;

// COMMON /areas/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonAreas {
    float ap[3];  // fortran ap(3) — 1-based
    int32_t imaxa;
};
extern CommonAreas cmn_areas;

// COMMON /avgdata/ — unique, 15 declaration site(s) in 15 file(s)
struct CommonAvgdata {
    float xnumavg;
    int32_t iteravg;
    float xnumavg2;
    int32_t ipertavg;
    int32_t iclcd;
    int32_t isubit_r;
};
extern CommonAvgdata cmn_avgdata;

// COMMON /axisym/ — unique, 19 declaration site(s) in 11 file(s)
struct CommonAxisym {
    int32_t iaxi2plane;
    int32_t iaxi2planeturb;
    int32_t istrongturbdis;
    int32_t iforcev0;
};
extern CommonAxisym cmn_axisym;

// COMMON /bbcom/ — unique, 2 declaration site(s) in 1 file(s)
struct CommonBbcom {
    int32_t nbbv;
    int32_t minpbb;
    int32_t maxlev;
    int32_t nwv;
    int32_t nbb;
    int32_t totbbv;
    float bbmin[3];  // fortran bbmin(3) — 1-based
    float bbmax[3];  // fortran bbmax(3) — 1-based
};
extern CommonBbcom cmn_bbcom;

// COMMON /bin/ — unique, 13 declaration site(s) in 13 file(s)
struct CommonBin {
    int32_t ibin;
    int32_t iblnk;
    int32_t iblnkfr;
    int32_t ip3dgrad;
};
extern CommonBin cmn_bin;

// COMMON /cfl/ — unique, 6 declaration site(s) in 6 file(s)
struct CommonCfl {
    float dt0;
    float dtold;
};
extern CommonCfl cmn_cfl;

// COMMON /cgns/ — unique, 12 declaration site(s) in 12 file(s)
struct CommonCgns {
    int32_t icgns;
    int32_t iccg;
    int32_t ibase;
    int32_t nzones;
    int32_t nsoluse;
    int32_t irind;
    int32_t jrind;
    int32_t krind;
};
extern CommonCgns cmn_cgns;

// COMMON /chk/ — unique, 8 declaration site(s) in 8 file(s)
struct CommonChk {
    int32_t ichk;
};
extern CommonChk cmn_chk;

// COMMON /chkbc/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonChkbc {
    int32_t isym;
    int32_t jsym;
    int32_t ksym;
    int32_t iwrap;
    int32_t jwrap;
    int32_t kwrap;
};
extern CommonChkbc cmn_chkbc;

// COMMON /complx/ — unique, 6 declaration site(s) in 6 file(s)
struct CommonComplx {
    float xmach_img;
    float alpha_img;
    float beta_img;
    float reue_img;
    float tinf_img;
    float geom_img;
    float surf_img;
    float xrotrate_img;
    float yrotrate_img;
    float zrotrate_img;
};
extern CommonComplx cmn_complx;

// COMMON /constit/ — unique, 12 declaration site(s) in 12 file(s)
struct CommonConstit {
    int32_t i_nonlin;
    float c_nonlin;
    float snonlin_lim;
    int32_t i_tauijs;
    int32_t i_qcr2000;
    int32_t i_qcr2013;
    int32_t i_qcr2013v;
};
extern CommonConstit cmn_constit;

// COMMON /conversion/ — unique, 34 declaration site(s) in 34 file(s)
struct CommonConversion {
    float radtodeg;
};
extern CommonConversion cmn_conversion;

// COMMON /cpurate/ — unique, 6 declaration site(s) in 6 file(s)
struct CommonCpurate {
    float rate[5];  // fortran rate(5) — 1-based
    float ratesub[5];  // fortran ratesub(5) — 1-based
    int32_t ncell[20];  // fortran ncell(20) — 1-based
};
extern CommonCpurate cmn_cpurate;

// COMMON /curvat/ — unique, 10 declaration site(s) in 10 file(s)
struct CommonCurvat {
    int32_t isarc2d;
    float sarccr3;
    int32_t ieasmcc2d;
    int32_t isstrc;
    float sstrc_crc;
    int32_t isar;
    float crot;
    int32_t isarc3d;
};
extern CommonCurvat cmn_curvat;

// COMMON /deformz/ — prefix, 18 declaration site(s) in 14 file(s)
//   note: 2 variants, all positional prefixes of the longest (10 members)
struct CommonDeformz {
    float beta1;
    float beta2;
    float alpha1;
    float alpha2;
    int32_t isktyp;
    int32_t negvol;
    int32_t meshdef;
    int32_t nsprgit;
    int32_t ndgrd;
    int32_t ndwrt;
};
extern CommonDeformz cmn_deformz;

// COMMON /degshf/ — unique, 5 declaration site(s) in 5 file(s)
struct CommonDegshf {
    int32_t ideg[3];  // fortran ideg(3) — 1-based
};
extern CommonDegshf cmn_degshf;

// COMMON /des/ — unique, 10 declaration site(s) in 10 file(s)
struct CommonDes {
    float cdes;
    int32_t ides;
    float cddes;
};
extern CommonDes cmn_des;

// COMMON /drag/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonDrag {
    float cdv;
    float cdp;
};
extern CommonDrag cmn_drag;

// COMMON /easmlim/ — unique, 4 declaration site(s) in 4 file(s)
struct CommonEasmlim {
    float cmulim;
};
extern CommonEasmlim cmn_easmlim;

// COMMON /easmv/ — unique, 10 declaration site(s) in 10 file(s)
struct CommonEasmv {
    float c10;
    float c11;
    float c2;
    float c3;
    float c4;
    float c5;
    float sigk1;
    float cmuc1;
    int32_t ieasm_type;
};
extern CommonEasmv cmn_easmv;

// COMMON /elastic/ — unique, 14 declaration site(s) in 14 file(s)
struct CommonElastic {
    int32_t ndefrm;
    int32_t naesrf;
};
extern CommonElastic cmn_elastic;

// COMMON /elastic_ss/ — unique, 8 declaration site(s) in 8 file(s)
struct CommonElasticSs {
    int32_t idef_ss;
};
extern CommonElasticSs cmn_elastic_ss;

// COMMON /entfix/ — unique, 7 declaration site(s) in 7 file(s)
struct CommonEntfix {
    float epsa_l;
    float epsa_r;
};
extern CommonEntfix cmn_entfix;

// COMMON /filenam/ — unique, 13 declaration site(s) in 13 file(s)
struct CommonFilenam {
    char grid[80];  // character*80
    char plt3dg[80];  // character*80
    char plt3dq[80];  // character*80
    char output[80];  // character*80
    char residual[80];  // character*80
    char turbres[80];  // character*80
    char blomx[80];  // character*80
    char output2[80];  // character*80
    char printout[80];  // character*80
    char pplunge[80];  // character*80
    char ovrlap[80];  // character*80
    char patch[80];  // character*80
    char restrt[80];  // character*80
    char subres[80];  // character*80
    char subtur[80];  // character*80
    char grdmov[80];  // character*80
    char alphahist[80];  // character*80
    char errfile[80];  // character*80
    char preout[80];  // character*80
    char aeinp[80];  // character*80
    char aeout[80];  // character*80
    char sdhist[80];  // character*80
    char avgg[80];  // character*80
    char avgq[80];  // character*80
};
extern CommonFilenam cmn_filenam;

// COMMON /filenam2/ — unique, 5 declaration site(s) in 5 file(s)
struct CommonFilenam2 {
    char avgq2[241];  // character*241
    char avgq2pert[241];  // character*241
    char clcds[241];  // character*241
    char clcdp[241];  // character*241
    char output_dir[241];  // character*241
};
extern CommonFilenam2 cmn_filenam2;

// COMMON /fluid/ — unique, 78 declaration site(s) in 73 file(s)
struct CommonFluid {
    float gamma;
    float gm1;
    float gp1;
    float gm1g;
    float gp1g;
    float ggm1;
};
extern CommonFluid cmn_fluid;

// COMMON /fluid2/ — unique, 37 declaration site(s) in 33 file(s)
struct CommonFluid2 {
    float pr;
    float prt;
    float cbar;
};
extern CommonFluid2 cmn_fluid2;

// COMMON /fsum/ — unique, 14 declaration site(s) in 14 file(s)
struct CommonFsum {
    float sref;
    float cref;
    float bref;
    float xmc;
    float ymc;
    float zmc;
};
extern CommonFsum cmn_fsum;

// COMMON /fullns/ — unique, 5 declaration site(s) in 5 file(s)
struct CommonFullns {
    int32_t ifullns;
};
extern CommonFullns cmn_fullns;

// COMMON /fvfds/ — unique, 11 declaration site(s) in 11 file(s)
struct CommonFvfds {
    float rkap0[3];  // fortran rkap0(3) — 1-based
    int32_t ifds[3];  // fortran ifds(3) — 1-based
};
extern CommonFvfds cmn_fvfds;

// COMMON /ghost/ — unique, 5 declaration site(s) in 5 file(s)
struct CommonGhost {
    int32_t irghost;
    int32_t iwghost;
};
extern CommonGhost cmn_ghost;

// COMMON /ginfo/ — rename, 25 declaration site(s) in 25 file(s)
//   note: member names differ across variants; suggested canonical from most-used variant — confirm via ReAct arbitration
//   note: arbitration: adopted suggestion — bc_period.f uses `lnbll` at position 40 (integer), identical type and offset to `lnbl` in all 24 other sites. Clear local alias to avoid a name clash; rename lnbll→lnbl in bc_period.f is correct.
struct CommonGinfo {
    int32_t jdim;
    int32_t kdim;
    int32_t idim;
    int32_t jj2;
    int32_t kk2;
    int32_t ii2;
    int32_t nblc;
    int32_t js;
    int32_t ks;
    int32_t is;
    int32_t je;
    int32_t ke;
    int32_t ie;
    int32_t lq;
    int32_t lqj0;
    int32_t lqk0;
    int32_t lqi0;
    int32_t lsj;
    int32_t lsk;
    int32_t lsi;
    int32_t lvol;
    int32_t ldtj;
    int32_t lx;
    int32_t ly;
    int32_t lz;
    int32_t lvis;
    int32_t lsnk0;
    int32_t lsni0;
    int32_t lq1;
    int32_t lqr;
    int32_t lblk;
    int32_t lxib;
    int32_t lsig;
    int32_t lsqtq;
    int32_t lg;
    int32_t ltj0;
    int32_t ltk0;
    int32_t lti0;
    int32_t lxkb;
    int32_t lnbl;
    int32_t lvj0;
    int32_t lvk0;
    int32_t lvi0;
    int32_t lbcj;
    int32_t lbck;
    int32_t lbci;
    int32_t lqc0;
    int32_t ldqc0;
    int32_t lxtbi;
    int32_t lxtbj;
    int32_t lxtbk;
    int32_t latbi;
    int32_t latbj;
    int32_t latbk;
    int32_t lbcdj;
    int32_t lbcdk;
    int32_t lbcdi;
    int32_t lxib2;
    int32_t lux;
    int32_t lcmuv;
    int32_t lvolj0;
    int32_t lvolk0;
    int32_t lvoli0;
    int32_t lxmdj;
    int32_t lxmdk;
    int32_t lxmdi;
    int32_t lvelg;
    int32_t ldeltj;
    int32_t ldeltk;
    int32_t ldelti;
    int32_t lxnm2;
    int32_t lynm2;
    int32_t lznm2;
    int32_t lxnm1;
    int32_t lynm1;
    int32_t lznm1;
    int32_t lqavg;
};
extern CommonGinfo cmn_ginfo;

// COMMON /ginfo2/ — unique, 12 declaration site(s) in 12 file(s)
struct CommonGinfo2 {
    int32_t lq2avg;
    int32_t iskip_blocks;
    int32_t inc_2d[3];  // fortran inc_2d(3) — 1-based
    int32_t inc_coarse[3];  // fortran inc_coarse(3) — 1-based
};
extern CommonGinfo2 cmn_ginfo2;

// COMMON /gridtrans/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonGridtrans {
    float roll_angle;
};
extern CommonGridtrans cmn_gridtrans;

// COMMON /hist/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonHist {
    float histry[4];  // fortran histry(4) — 1-based
};
extern CommonHist cmn_hist;

// COMMON /igrdtyp/ — unique, 30 declaration site(s) in 30 file(s)
struct CommonIgrdtyp {
    int32_t ip3dgrd;
    int32_t ialph;
};
extern CommonIgrdtyp cmn_igrdtyp;

// COMMON /info/ — rename, 116 declaration site(s) in 89 file(s)
//   note: member names differ across variants; suggested canonical from most-used variant — confirm via ReAct arbitration
//   note: arbitration: adopted suggestion — module_kwstm.f90 declares module-level REAL variables named `alpha` and `beta` (lines 41-42), forcing the COMMON members at the same positions to be spelled `alpha__` and `beta__` to avoid name collision within the module. Same type (real) and same storage offsets as the canonical `alpha`/`beta`. Rename alpha__→alpha, beta__→beta in module_kwstm.f90.
struct CommonInfo {
    float title[20];  // fortran title(20) — 1-based
    float rkap[3];  // fortran rkap(3) — 1-based
    float xmach;
    float alpha;
    float beta;
    float dt;
    float fmax;
    int32_t nit;
    int32_t ntt;
    int32_t idiag[3];  // fortran idiag(3) — 1-based
    int32_t nitfo;
    int32_t iflagts;
    int32_t iflim[3];  // fortran iflim(3) — 1-based
    int32_t nres;
    int32_t levelb[5];  // fortran levelb(5) — 1-based
    int32_t mgflag;
    int32_t iconsf;
    int32_t mseq;
    int32_t ncyc1[5];  // fortran ncyc1(5) — 1-based
    int32_t levelt[5];  // fortran levelt(5) — 1-based
    int32_t nitfo1[5];  // fortran nitfo1(5) — 1-based
    int32_t ngam;
    int32_t nsm[5];  // fortran nsm(5) — 1-based
    int32_t iipv;
};
extern CommonInfo cmn_info;

// COMMON /initfac/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonInitfac {
    float scal_ic;
};
extern CommonInitfac cmn_initfac;

// COMMON /is_blockbc/ — unique, 6 declaration site(s) in 6 file(s)
struct CommonIsBlockbc {
    int32_t is_blk[5];  // fortran is_blk(5) — 1-based
    int32_t ie_blk[5];  // fortran ie_blk(5) — 1-based
    int32_t ivolint;
};
extern CommonIsBlockbc cmn_is_blockbc;

// COMMON /is_dpatch/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonIsDpatch {
    int32_t maxdcnt;
};
extern CommonIsDpatch cmn_is_dpatch;

// COMMON /is_embedbc/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonIsEmbedbc {
    int32_t is_emb[5];  // fortran is_emb(5) — 1-based
    int32_t ie_emb[5];  // fortran ie_emb(5) — 1-based
    int32_t nbcemb;
};
extern CommonIsEmbedbc cmn_is_embedbc;

// COMMON /is_patch/ — unique, 5 declaration site(s) in 5 file(s)
struct CommonIsPatch {
    int32_t is_pat[5];  // fortran is_pat(5) — 1-based
    int32_t ie_pat[5];  // fortran ie_pat(5) — 1-based
    int32_t ipatch1st;
};
extern CommonIsPatch cmn_is_patch;

// COMMON /is_perbc/ — unique, 4 declaration site(s) in 4 file(s)
struct CommonIsPerbc {
    int32_t is_prd[5];  // fortran is_prd(5) — 1-based
    int32_t ie_prd[5];  // fortran ie_prd(5) — 1-based
    int32_t nbcprd;
};
extern CommonIsPerbc cmn_is_perbc;

// COMMON /iupdate/ — unique, 4 declaration site(s) in 4 file(s)
struct CommonIupdate {
    int32_t iupdatemean;
};
extern CommonIupdate cmn_iupdate;

// COMMON /ivals/ — unique, 55 declaration site(s) in 49 file(s)
struct CommonIvals {
    float p0;
    float rho0;
    float c0;
    float u0;
    float v0;
    float w0;
    float et0;
    float h0;
    float pt0;
    float rhot0;
    float qiv[5];  // fortran qiv(5) — 1-based
    float tur10[7];  // fortran tur10(7) — 1-based
};
extern CommonIvals cmn_ivals;

// COMMON /key/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonKey {
    int32_t nkey;
};
extern CommonKey cmn_key;

// COMMON /konew/ — unique, 9 declaration site(s) in 9 file(s)
struct CommonKonew {
    int32_t ikoprod;
    int32_t isstdenom;
    float pklimterm;
    int32_t ibeta8kzeta;
    int32_t i_bsl;
    int32_t keepambient;
    float re_thetat0;
    int32_t i_wilcox06;
    int32_t i_wilcox06_chiw;
    int32_t i_turbprod_kterm;
    int32_t i_catris_kw;
    float prod2d3dtrace;
    int32_t i_compress_correct;
    int32_t isstsf;
    int32_t i_wilcox98;
    int32_t i_wilcox98_chiw;
    int32_t isst2003;
};
extern CommonKonew cmn_konew;

// COMMON /lam/ — prefix, 12 declaration site(s) in 12 file(s)
//   note: 2 variants, all positional prefixes of the longest (7 members)
struct CommonLam {
    int32_t ilamlo;
    int32_t ilamhi;
    int32_t jlamlo;
    int32_t jlamhi;
    int32_t klamlo;
    int32_t klamhi;
    int32_t i_lam_forcezero;
};
extern CommonLam cmn_lam;

// COMMON /lesinfo/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonLesinfo {
    int32_t les_model;
    int32_t les_wallscale;
    float cs_smagorinsky;
    float cs_wale;
    float cs_vreman;
};
extern CommonLesinfo cmn_lesinfo;

// COMMON /maxiv/ — unique, 47 declaration site(s) in 43 file(s)
struct CommonMaxiv {
    int32_t ivmx;
};
extern CommonMaxiv cmn_maxiv;

// COMMON /memory/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonMemory {
    int32_t memadd;
    int32_t memaddi;
};
extern CommonMemory cmn_memory;

// COMMON /memry/ — unique, 6 declaration site(s) in 6 file(s)
struct CommonMemry {
    int32_t lowmem_ux;
};
extern CommonMemry cmn_memry;

// COMMON /mgrd/ — unique, 75 declaration site(s) in 75 file(s)
struct CommonMgrd {
    int32_t levt;
    int32_t kode;
    int32_t mode;
    int32_t ncyc;
    int32_t mtt;
    int32_t icyc;
    int32_t level;
    int32_t lglobal;
};
extern CommonMgrd cmn_mgrd;

// COMMON /mgv/ — unique, 4 declaration site(s) in 4 file(s)
struct CommonMgv {
    float epsssc[3];  // fortran epsssc(3) — 1-based
    float epsssr[3];  // fortran epsssr(3) — 1-based
    int32_t issc;
    int32_t issr;
};
extern CommonMgv cmn_mgv;

// COMMON /mms/ — unique, 9 declaration site(s) in 9 file(s)
struct CommonMms {
    int32_t iexact_trunc;
    int32_t iexact_disc;
    int32_t iexact_ring;
};
extern CommonMms cmn_mms;

// COMMON /moov/ — prefix, 19 declaration site(s) in 19 file(s)
//   note: 2 variants, all positional prefixes of the longest (6 members)
struct CommonMoov {
    int32_t movie;
    int32_t nframes;
    int32_t icall1;
    int32_t lhdr;
    int32_t icoarsemovie;
    int32_t i2dmovie;
};
extern CommonMoov cmn_moov;

// COMMON /moovcrs2d/ — unique, 4 declaration site(s) in 4 file(s)
struct CommonMoovcrs2d {
    int32_t icallcrs;
    int32_t icall2d;
};
extern CommonMoovcrs2d cmn_moovcrs2d;

// COMMON /motionmc/ — unique, 10 declaration site(s) in 10 file(s)
struct CommonMotionmc {
    float xmc0;
    float ymc0;
    float zmc0;
    float utransmc;
    float vtransmc;
    float wtransmc;
    float omegaxmc;
    float omegaymc;
    float omegazmc;
    float xorigmc;
    float yorigmc;
    float zorigmc;
    float xorig0mc;
    float yorig0mc;
    float zorig0mc;
    float thetaxmc;
    float thetaymc;
    float thetazmc;
    float dxmxmc;
    float dymxmc;
    float dzmxmc;
    float dthxmxmc;
    float dthymxmc;
    float dthzmxmc;
    float rfreqtmc;
    float rfreqrmc;
    int32_t itransmc;
    int32_t irotatmc;
    float time2mc;
};
extern CommonMotionmc cmn_motionmc;

// COMMON /mydist2/ — unique, 18 declaration site(s) in 14 file(s)
struct CommonMydist2 {
    int32_t nnodes;
    int32_t myhost;
    int32_t myid;
    int32_t mycomm;
};
extern CommonMydist2 cmn_mydist2;

// COMMON /ncyct/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonNcyct {
    int32_t ncyctot;
};
extern CommonNcyct cmn_ncyct;

// COMMON /nfablk/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonNfablk {
    int32_t nfajki[3];  // fortran nfajki(3) — 1-based
};
extern CommonNfablk cmn_nfablk;

// COMMON /noninertial/ — unique, 9 declaration site(s) in 9 file(s)
struct CommonNoninertial {
    float xcentrot;
    float ycentrot;
    float zcentrot;
    float xrotrate;
    float yrotrate;
    float zrotrate;
    int32_t noninflag;
};
extern CommonNoninertial cmn_noninertial;

// COMMON /params/ — unique, 5 declaration site(s) in 5 file(s)
struct CommonParams {
    int32_t lmaxgr;
    int32_t lmaxbl;
    int32_t lmxseg;
    int32_t lmaxcs;
    int32_t lnplts;
    int32_t lmxbli;
    int32_t lmaxxe;
    int32_t lnsub1;
    int32_t lintmx;
    int32_t lmxxe;
    int32_t liitot;
    int32_t isum;
    int32_t lncycm;
    int32_t isum_n;
    int32_t lminnode;
    int32_t isumi;
    int32_t isumi_n;
    int32_t lmptch;
    int32_t lmsub1;
    int32_t lintmax;
    int32_t libufdim;
    int32_t lnbuf;
    int32_t llbcprd;
    int32_t llbcemb;
    int32_t llbcrad;
    int32_t lnmds;
    int32_t lmaxaes;
    int32_t lnslave;
    int32_t lmxsegdg;
    int32_t lnmaster;
};
extern CommonParams cmn_params;

// COMMON /plot3dtyp/ — unique, 6 declaration site(s) in 6 file(s)
struct CommonPlot3dtyp {
    int32_t ifunct;
};
extern CommonPlot3dtyp cmn_plot3dtyp;

// COMMON /precond/ — unique, 19 declaration site(s) in 19 file(s)
struct CommonPrecond {
    float cprec;
    float uref;
    float avn;
};
extern CommonPrecond cmn_precond;

// COMMON /proces/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonProces {
    int32_t numprocs;
};
extern CommonProces cmn_proces;

// COMMON /random_input/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonRandomInput {
    float randomize;
};
extern CommonRandomInput cmn_random_input;

// COMMON /rbstmt1/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonRbstmt1 {
    float bmatrb[16];  // fortran bmatrb(4,4) column-major, wrap with FortranArray2DRef
    float gforcnrb[4];  // fortran gforcnrb(4) — 1-based
    float gforcnmrb[4];  // fortran gforcnmrb(4) — 1-based
    float gforcsrb[4];  // fortran gforcsrb(4) — 1-based
    float stmrb[16];  // fortran stmrb(4,4) column-major, wrap with FortranArray2DRef
    float stmirb[16];  // fortran stmirb(4,4) column-major, wrap with FortranArray2DRef
    float xsrb[4];  // fortran xsrb(4) — 1-based
    float xxnrb[4];  // fortran xxnrb(4) — 1-based
    float xnmrb[4];  // fortran xnmrb(4) — 1-based
    float x0rb[4];  // fortran x0rb(4) — 1-based
};
extern CommonRbstmt1 cmn_rbstmt1;

// COMMON /rbstmt2/ — unique, 7 declaration site(s) in 7 file(s)
struct CommonRbstmt2 {
    float tmass;
    float yinert;
    float uinfrb;
    float qinfrb;
    float greflrb;
    float gaccel;
    float crefrb;
    float xtmref;
    float areat;
};
extern CommonRbstmt2 cmn_rbstmt2;

// COMMON /reystressmodel/ — unique, 7 declaration site(s) in 7 file(s)
struct CommonReystressmodel {
    int32_t issglrrw2012;
    int32_t i_sas_rsm;
    int32_t i_yapterm;
};
extern CommonReystressmodel cmn_reystressmodel;

// COMMON /reyue/ — prefix, 95 declaration site(s) in 75 file(s)
//   note: 2 variants, all positional prefixes of the longest (3 members)
struct CommonReyue {
    float reue;
    float tinf;
    int32_t ivisc[3];  // fortran ivisc(3) — 1-based
};
extern CommonReyue cmn_reyue;

// COMMON /rigidbody/ — unique, 4 declaration site(s) in 4 file(s)
struct CommonRigidbody {
    int32_t irigb;
    int32_t irbtrim;
};
extern CommonRigidbody cmn_rigidbody;

// COMMON /sa_options/ — unique, 4 declaration site(s) in 4 file(s)
struct CommonSaOptions {
    int32_t i_saneg;
    int32_t i_sanoft2;
    float sa_cw2;
    float sa_cw3;
    float sa_cv1;
    float sa_ct3;
    float sa_ct4;
    float sa_cb1;
    float sa_cb2;
    float sa_sigma;
    float sa_karman;
};
extern CommonSaOptions cmn_sa_options;

// COMMON /save/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonSave {
    int32_t locv;
    int32_t ireq;
};
extern CommonSave cmn_save;

// COMMON /savnint/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonSavnint {
    int32_t ninter0;
};
extern CommonSavnint cmn_savnint;

// COMMON /sgminmax/ — unique, 2 declaration site(s) in 1 file(s)
struct CommonSgminmax {
    float rmin;
    float rmax;
};
extern CommonSgminmax cmn_sgminmax;

// COMMON /singular/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonSingular {
    float atol;
};
extern CommonSingular cmn_singular;

// COMMON /sklt1/ — unique, 5 declaration site(s) in 5 file(s)
struct CommonSklt1 {
    int32_t isklt1;
};
extern CommonSklt1 cmn_sklt1;

// COMMON /sklton/ — unique, 72 declaration site(s) in 72 file(s)
struct CommonSklton {
    int32_t isklton;
};
extern CommonSklton cmn_sklton;

// COMMON /sminn/ — unique, 5 declaration site(s) in 5 file(s)
struct CommonSminn {
    int32_t isminc;
    int32_t ismincforce;
};
extern CommonSminn cmn_sminn;

// COMMON /sourceterm/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonSourceterm {
    float xdir_only_source;
};
extern CommonSourceterm cmn_sourceterm;

// COMMON /specialtop_kmax1001/ — unique, 4 declaration site(s) in 4 file(s)
struct CommonSpecialtopKmax1001 {
    int32_t i_specialtop_kmax1001;
    float a_specialtop_kmax1001;
    float xc_specialtop_kmax1001;
    float sig_specialtop_kmax1001;
    float vtp_specialtop_kmax1001;
    float wc_specialtop_kmax1001;
    float fac_specialtop_kmax1001;
    float cc_specialtop_kmax1001;
    float xerf_specialtop_kmax1001;
    float sigerf_specialtop_kmax1001;
};
extern CommonSpecialtopKmax1001 cmn_specialtop_kmax1001;

// COMMON /subit/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonSubit {
    float cltsub;
    float cdtsub;
    float cxtsub;
    float cytsub;
    float cztsub;
    float cmxtsub;
    float cmytsub;
    float cmztsub;
    float cdptsub;
    float cdvtsub;
    float sxsub;
    float sysub;
    float szsub;
    float stotsub;
    float fmdotsub;
    float cfxpsub;
    float cfypsub;
    float cfzpsub;
    float cflpsub;
    float cfdpsub;
    float cftpsub;
    float cfxvsub;
    float cfyvsub;
    float cfzvsub;
    float cflvsub;
    float cfdvsub;
    float cftvsub;
    float cfxmomsub;
    float cfymomsub;
    float cfzmomsub;
    float cflmomsub;
    float cfdmomsub;
    float cftmomsub;
    float cfxtotsub;
    float cfytotsub;
    float cfztotsub;
    float cfdtotsub;
    float cfltotsub;
    float cfttotsub;
};
extern CommonSubit cmn_subit;

// COMMON /tacos/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonTacos {
    int32_t iretry;
};
extern CommonTacos cmn_tacos;

// COMMON /time1/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonTime1 {
    float tim[9];  // fortran tim(3,3) column-major, wrap with FortranArray2DRef
    float tm[3];  // fortran tm(3) — 1-based
};
extern CommonTime1 cmn_time1;

// COMMON /tol/ — rename, 7 declaration site(s) in 7 file(s)
//   note: member names differ across variants; suggested canonical from most-used variant — confirm via ReAct arbitration
//   note: arbitration: adopted suggestion — collapse.f places `eps` at position 4 (canonical `epscoll`); rechk.f places `eps` at position 3 (canonical `epsreen`). Both are real, same offsets. Local alias `eps` used in each file for the one tolerance value it needs. Renames eps→epscoll in collapse.f and eps→epsreen in rechk.f are correct.
struct CommonTol {
    float epsc;
    float epsc0;
    float epsreen;
    float epscoll;
};
extern CommonTol cmn_tol;

// COMMON /tracer/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonTracer {
    int32_t itrace;
};
extern CommonTracer cmn_tracer;

// COMMON /trim/ — unique, 9 declaration site(s) in 9 file(s)
struct CommonTrim {
    float dmtrmn;
    float dmtrmnm;
    float dlcln;
    float dlclnm;
    float trtol;
    float cmy;
    float cnw;
    float alf0;
    float alf1;
    float dzdt;
    float thtd0;
    float thtd1;
    float zrg0;
    float zrg1;
    float dtrmsmx;
    float dtrmsmn;
    float dalfmx;
    float ddtmx;
    float ddtrm0;
    float ddtrm1;
    int32_t itrmt;
    int32_t itrminc;
    float fp[16];  // fortran fp(4,4) column-major, wrap with FortranArray2DRef
    float tp[16];  // fortran tp(4,4) column-major, wrap with FortranArray2DRef
    float zlfct;
    float epstr;
    float relax;
    int32_t ittrst;
};
extern CommonTrim cmn_trim;

// COMMON /trim1/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonTrim1 {
    float dcl[5000];  // fortran dcl(5000) — 1-based
    float ddclda[5000];  // fortran ddclda(5000) — 1-based
    float ddcmda[5000];  // fortran ddcmda(5000) — 1-based
    float r33;
    float r44;
    int32_t ittr;
    float dcm[5000];  // fortran dcm(5000) — 1-based
    float dd[5000];  // fortran dd(5000) — 1-based
    float da[5000];  // fortran da(5000) — 1-based
    float a11;
    float a12;
    float a22;
    float r11;
    float r22;
};
extern CommonTrim1 cmn_trim1;

// COMMON /turbconv/ — prefix, 20 declaration site(s) in 17 file(s)
//   note: 3 variants, all positional prefixes of the longest (13 members)
struct CommonTurbconv {
    float cflturb[7];  // fortran cflturb(7) — 1-based
    float edvislim;
    int32_t iturbprod;
    int32_t nsubturb;
    int32_t nfreeze;
    int32_t iwarneddy;
    int32_t itime2read;
    int32_t itaturb;
    float tur1cut;
    float tur2cut;
    int32_t iturbord;
    float tur1cutlev;
    float tur2cutlev;
};
extern CommonTurbconv cmn_turbconv;

// COMMON /twod/ — unique, 61 declaration site(s) in 48 file(s)
struct CommonTwod {
    int32_t i2d;
};
extern CommonTwod cmn_twod;

// COMMON /unit5/ — unique, 9 declaration site(s) in 9 file(s)
struct CommonUnit5 {
    int32_t iunit5;
};
extern CommonUnit5 cmn_unit5;

// COMMON /unst/ — unique, 59 declaration site(s) in 55 file(s)
struct CommonUnst {
    float time;
    float cfltau;
    int32_t ntstep;
    int32_t ita;
    int32_t iunst;
    float cfltau0;
    float cfltaumax;
};
extern CommonUnst cmn_unst;

// COMMON /wallfun/ — unique, 16 declaration site(s) in 15 file(s)
struct CommonWallfun {
    int32_t iwf[3];  // fortran iwf(3) — 1-based
};
extern CommonWallfun cmn_wallfun;

// COMMON /wallvel_2034/ — unique, 4 declaration site(s) in 4 file(s)
struct CommonWallvel2034 {
    float uub_2034;
    float vvb_2034;
    float wwb_2034;
    float vvb_xaxisrot2034;
};
extern CommonWallvel2034 cmn_wallvel_2034;

// COMMON /wrbl/ — unique, 5 declaration site(s) in 5 file(s)
struct CommonWrbl {
    int32_t nwrest;
};
extern CommonWrbl cmn_wrbl;

// COMMON /wrestq/ — unique, 6 declaration site(s) in 6 file(s)
struct CommonWrestq {
    int32_t irest;
    int32_t irest2;
};
extern CommonWrestq cmn_wrestq;

// COMMON /writestuff/ — unique, 4 declaration site(s) in 4 file(s)
struct CommonWritestuff {
    int32_t ifort50write;
    int32_t j_ifort50write;
    int32_t i_ifort50write;
};
extern CommonWritestuff cmn_writestuff;

// COMMON /ypinfo/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonYpinfo {
    float ypsumb;
    float ypsumsqb;
    float ypmaxb;
    float ypminb;
    float dnmaxb;
    float dnminb;
    float ypchk;
    int32_t nptsb;
    int32_t jypmaxb;
    int32_t kypmaxb;
    int32_t iypmaxb;
    int32_t jypminb;
    int32_t kypminb;
    int32_t iypminb;
    int32_t jdnmaxb;
    int32_t kdnmaxb;
    int32_t idnmaxb;
    int32_t jdnminb;
    int32_t kdnminb;
    int32_t idnminb;
    int32_t nypchkb;
};
extern CommonYpinfo cmn_ypinfo;

// COMMON /zero/ — unique, 27 declaration site(s) in 27 file(s)
struct CommonZero {
    int32_t iexp;
};
extern CommonZero cmn_zero;
