// SPDX-License-Identifier: Apache-2.0
// Copyright 2001 United States Government as represented by the
// Administrator of the National Aeronautics and Space Administration.
// Copyright 2026 Jason Huang and cfl3d-cpp contributors (C++ translation).
// Licensed under the Apache License, Version 2.0 (see the LICENSE file).
//
// common_blocks.h — auto-generated by f2cpp common_mapper.
// One struct per Fortran COMMON block: defined once,
// included everywhere. DO NOT EDIT BY HAND.
#pragma once
#include <complex>
#include <cstddef>
#include <cstdint>

// COMMON /alphait/ — conflict, 3 declaration site(s) in 3 file(s)
//   note: 2 incompatible layouts; may belong to different programs (check linkage) or need manual unification
//   note: arbitration: deferred — Genuine structural conflict: variant 0 (cfl3d_to_tlns3d.F, tlns3d_to_cfl3d.F) starts with cltarg:real at offset 0, while variant 1 (readkey.F) starts with ialphit:integer at offset 0 — incompatible at every position. All three files are linked into the same executable (main.F calls sizer→readkey and splitter→cfl3d_to_tlns3d/tlns3d_to_cfl3d). Members rlxalph and dalpha appear only in readkey.F; resupdt, cltol, dcldal, alphalast, nttlast appear only in the other two. Cannot be resolved by renaming; requires manual source-level unification of the two layouts.
struct CommonAlphait {
    float cltarg;
    float resupdt;
    float cltol;
    float dalim;
    float dcldal;
    float alphalast;
    int32_t ialphit;
    int32_t nttlast;
    int32_t icycupdt;
};
extern CommonAlphait cmn_alphait;

// COMMON /avgdata/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonAvgdata {
    float xnumavg;
    int32_t iteravg;
    float xnumavg2;
    int32_t ipertavg;
    int32_t iclcd;
    int32_t isubit_r;
};
extern CommonAvgdata cmn_avgdata;

// COMMON /axisym/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonAxisym {
    int32_t iaxi2plane;
    int32_t iaxi2planeturb;
    int32_t istrongturbdis;
    int32_t iforcev0;
};
extern CommonAxisym cmn_axisym;

// COMMON /bin/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonBin {
    int32_t ibin;
    int32_t iblnk;
    int32_t iblnkfr;
    int32_t ip3dgrad;
};
extern CommonBin cmn_bin;

// COMMON /block/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonBlock {
    int32_t nbltop;
};
extern CommonBlock cmn_block;

// COMMON /cflfiles/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonCflfiles {
    char gridin[80];  // character*80
    char plt3dg[80];  // character*80
    char plt3dq[80];  // character*80
    char output[80];  // character*80
    char resid[80];  // character*80
    char turbres[80];  // character*80
    char blomx[80];  // character*80
    char output2[80];  // character*80
    char printout[80];  // character*80
    char pplunge[80];  // character*80
    char ovrlap[80];  // character*80
    char patch[80];  // character*80
    char restrt[80];  // character*80
    char gridout[80];  // character*80
    char sdgridin[80];  // character*80
    char sdgridout[80];  // character*80
    char dovrlap[80];  // character*80
    char dpatch[80];  // character*80
    char dresid[80];  // character*80
};
extern CommonCflfiles cmn_cflfiles;

// COMMON /cgns/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonCgns {
    int32_t icgns;
    int32_t iccg;
    int32_t ibase;
    int32_t nzones;
    int32_t nsoluse;
    int32_t irind;
    int32_t jrind;
    int32_t krind;
};
extern CommonCgns cmn_cgns;

// COMMON /chk1/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonChk1 {
    int32_t ncgmax;
};
extern CommonChk1 cmn_chk1;

// COMMON /complx/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonComplx {
    float xmach_img;
    float alpha_img;
    float beta_img;
    float reue_img;
    float tinf_img;
    float geom_img;
    float surf_img;
    float xrotrate_img;
    float yrotrate_img;
    float zrotrate_img;
};
extern CommonComplx cmn_complx;

// COMMON /constit/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonConstit {
    int32_t i_nonlin;
    float c_nonlin;
    float snonlin_lim;
    int32_t i_tauijs;
    int32_t i_qcr2000;
    int32_t i_qcr2013;
    int32_t i_qcr2013v;
};
extern CommonConstit cmn_constit;

// COMMON /curvat/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonCurvat {
    int32_t isarc2d;
    float sarccr3;
    int32_t ieasmcc2d;
    int32_t isstrc;
    float sstrc_crc;
    int32_t isar;
    float crot;
    int32_t isarc3d;
};
extern CommonCurvat cmn_curvat;

// COMMON /deformz/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonDeformz {
    float beta1;
    float beta2;
    float alpha1;
    float alpha2;
    int32_t isktyp;
    int32_t negvol;
    int32_t meshdef;
    int32_t nsprgit;
    int32_t ndgrd;
    int32_t ndwrt;
};
extern CommonDeformz cmn_deformz;

// COMMON /des/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonDes {
    float cdes;
    int32_t ides;
    float cddes;
};
extern CommonDes cmn_des;

// COMMON /easmlim/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonEasmlim {
    float cmulim;
};
extern CommonEasmlim cmn_easmlim;

// COMMON /easmv/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonEasmv {
    float c10;
    float c11;
    float c2;
    float c3;
    float c4;
    float c5;
    float sigk1;
    float cmuc1;
    int32_t ieasm_type;
};
extern CommonEasmv cmn_easmv;

// COMMON /elastic_ss/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonElasticSs {
    int32_t idef_ss;
};
extern CommonElasticSs cmn_elastic_ss;

// COMMON /entfix/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonEntfix {
    float epsa_l;
    float epsa_r;
};
extern CommonEntfix cmn_entfix;

// COMMON /filenam2/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonFilenam2 {
    char avgq2[241];  // character*241
    char avgq2pert[241];  // character*241
    char clcds[241];  // character*241
    char clcdp[241];  // character*241
    char output_dir[241];  // character*241
};
extern CommonFilenam2 cmn_filenam2;

// COMMON /fluid/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonFluid {
    float gamma;
    float gm1;
    float gp1;
    float gm1g;
    float gp1g;
    float ggm1;
};
extern CommonFluid cmn_fluid;

// COMMON /fluid2/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonFluid2 {
    float pr;
    float prt;
    float cbar;
};
extern CommonFluid2 cmn_fluid2;

// COMMON /fullns/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonFullns {
    int32_t ifullns;
};
extern CommonFullns cmn_fullns;

// COMMON /ghost/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonGhost {
    int32_t irghost;
    int32_t iwghost;
};
extern CommonGhost cmn_ghost;

// COMMON /ginfo2/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonGinfo2 {
    int32_t lq2avg;
    int32_t iskip_blocks;
    int32_t inc_2d[3];  // fortran inc_2d(3) — 1-based
    int32_t inc_coarse[3];  // fortran inc_coarse(3) — 1-based
};
extern CommonGinfo2 cmn_ginfo2;

// COMMON /grdinfo/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonGrdinfo {
    int32_t nbloc;
};
extern CommonGrdinfo cmn_grdinfo;

// COMMON /gridtrans/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonGridtrans {
    float roll_angle;
};
extern CommonGridtrans cmn_gridtrans;

// COMMON /info/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonInfo {
    float title[20];  // fortran title(20) — 1-based
    float rkap[3];  // fortran rkap(3) — 1-based
    float xmach;
    float alpha;
    float beta;
    float dt;
    float fmax;
    int32_t nit;
    int32_t ntt;
    int32_t idiag[3];  // fortran idiag(3) — 1-based
    int32_t nitfo;
    int32_t iflagts;
    int32_t iflim[3];  // fortran iflim(3) — 1-based
    int32_t nres;
    int32_t levelb[5];  // fortran levelb(5) — 1-based
    int32_t mgflag;
    int32_t iconsf;
    int32_t mseq;
    int32_t ncyc1[5];  // fortran ncyc1(5) — 1-based
    int32_t levelt[5];  // fortran levelt(5) — 1-based
    int32_t nitfo1[5];  // fortran nitfo1(5) — 1-based
    int32_t ngam;
    int32_t nsm[5];  // fortran nsm(5) — 1-based
    int32_t iipv;
};
extern CommonInfo cmn_info;

// COMMON /info2/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonInfo2 {
    float tinf;
    float reue;
    float c2spe;
    float bref;
    float cref;
    float sref;
    float xmc;
    float ymc;
    float zmc;
    float rfreq;
    float alphau;
    float cloc;
    float cfltau;
};
extern CommonInfo2 cmn_info2;

// COMMON /info3/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonInfo3 {
    int32_t ncg;
    int32_t isnd;
    int32_t ialph;
    int32_t irest;
    int32_t iunst;
    int32_t ntstep;
    int32_t ita;
    int32_t ihstry;
    int32_t nplot3d;
    int32_t nprint;
    int32_t nwrest;
    int32_t ichk;
    int32_t i2d;
    int32_t mglev[5];  // fortran mglev(5) — 1-based
    int32_t nem[5];  // fortran nem(5) — 1-based
    int32_t mitl[25];  // fortran mitl(5,5) column-major, wrap with FortranArray2DRef
    int32_t mtt;
    int32_t ndv;
    int32_t isdform;
    int32_t ip3dgrd;
    int32_t iplt3dtyp;
};
extern CommonInfo3 cmn_info3;

// COMMON /initfac/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonInitfac {
    float scal_ic;
};
extern CommonInitfac cmn_initfac;

// COMMON /is_blockbc/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonIsBlockbc {
    int32_t is_blk[5];  // fortran is_blk(5) — 1-based
    int32_t ie_blk[5];  // fortran ie_blk(5) — 1-based
    int32_t ivolint;
};
extern CommonIsBlockbc cmn_is_blockbc;

// COMMON /is_patch/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonIsPatch {
    int32_t is_pat[5];  // fortran is_pat(5) — 1-based
    int32_t ie_pat[5];  // fortran ie_pat(5) — 1-based
    int32_t ipatch1st;
};
extern CommonIsPatch cmn_is_patch;

// COMMON /iupdate/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonIupdate {
    int32_t iupdatemean;
};
extern CommonIupdate cmn_iupdate;

// COMMON /ivals/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonIvals {
    float p0;
    float rho0;
    float c0;
    float u0;
    float v0;
    float w0;
    float et0;
    float h0;
    float pt0;
    float rhot0;
    float qiv[5];  // fortran qiv(5) — 1-based
    float tur10[7];  // fortran tur10(7) — 1-based
};
extern CommonIvals cmn_ivals;

// COMMON /key/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonKey {
    int32_t nkey;
};
extern CommonKey cmn_key;

// COMMON /konew/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonKonew {
    int32_t ikoprod;
    int32_t isstdenom;
    float pklimterm;
    int32_t ibeta8kzeta;
    int32_t i_bsl;
    int32_t keepambient;
    float re_thetat0;
    int32_t i_wilcox06;
    int32_t i_wilcox06_chiw;
    int32_t i_turbprod_kterm;
    int32_t i_catris_kw;
    float prod2d3dtrace;
    int32_t i_compress_correct;
    int32_t isstsf;
    int32_t i_wilcox98;
    int32_t i_wilcox98_chiw;
    int32_t isst2003;
};
extern CommonKonew cmn_konew;

// COMMON /lam/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonLam {
    int32_t ilamlo;
    int32_t ilamhi;
    int32_t jlamlo;
    int32_t jlamhi;
    int32_t klamlo;
    int32_t klamhi;
    int32_t i_lam_forcezero;
};
extern CommonLam cmn_lam;

// COMMON /lesinfo/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonLesinfo {
    int32_t les_model;
    int32_t les_wallscale;
    float cs_smagorinsky;
    float cs_wale;
    float cs_vreman;
};
extern CommonLesinfo cmn_lesinfo;

// COMMON /maxiv/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonMaxiv {
    int32_t ivmx;
};
extern CommonMaxiv cmn_maxiv;

// COMMON /memory/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonMemory {
    int32_t memadd;
    int32_t memaddi;
};
extern CommonMemory cmn_memory;

// COMMON /memry/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonMemry {
    int32_t lowmem_ux;
};
extern CommonMemry cmn_memry;

// COMMON /mgv/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonMgv {
    float epsssc[3];  // fortran epsssc(3) — 1-based
    float epsssr[3];  // fortran epsssr(3) — 1-based
    int32_t issc;
    int32_t issr;
};
extern CommonMgv cmn_mgv;

// COMMON /mms/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonMms {
    int32_t iexact_trunc;
    int32_t iexact_disc;
    int32_t iexact_ring;
};
extern CommonMms cmn_mms;

// COMMON /moov/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonMoov {
    int32_t movie;
    int32_t nframes;
    int32_t icall1;
    int32_t lhdr;
    int32_t icoarsemovie;
    int32_t i2dmovie;
};
extern CommonMoov cmn_moov;

// COMMON /mydist2/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonMydist2 {
    int32_t nnodes;
    int32_t myhost;
    int32_t myid;
    int32_t mycomm;
};
extern CommonMydist2 cmn_mydist2;

// COMMON /noninertial/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonNoninertial {
    float xcentrot;
    float ycentrot;
    float zcentrot;
    float xrotrate;
    float yrotrate;
    float zrotrate;
    int32_t noninflag;
};
extern CommonNoninertial cmn_noninertial;

// COMMON /oldbl/ — unique, 3 declaration site(s) in 3 file(s)
struct CommonOldbl {
    int32_t noldbl;
};
extern CommonOldbl cmn_oldbl;

// COMMON /plot3dtyp/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonPlot3dtyp {
    int32_t ifunct;
};
extern CommonPlot3dtyp cmn_plot3dtyp;

// COMMON /precon1/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonPrecon1 {
    float cprec;
    float uref;
    float avn;
    int32_t iprecon;
};
extern CommonPrecon1 cmn_precon1;

// COMMON /precond/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonPrecond {
    float cprec;
    float uref;
    float avn;
};
extern CommonPrecond cmn_precond;

// COMMON /random_input/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonRandomInput {
    float randomize;
};
extern CommonRandomInput cmn_random_input;

// COMMON /rbstmt2/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonRbstmt2 {
    float tmass;
    float yinert;
    float uinfrb;
    float qinfrb;
    float greflrb;
    float gaccel;
    float crefrb;
    float xtmref;
    float areat;
};
extern CommonRbstmt2 cmn_rbstmt2;

// COMMON /reystressmodel/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonReystressmodel {
    int32_t issglrrw2012;
    int32_t i_sas_rsm;
    int32_t i_yapterm;
};
extern CommonReystressmodel cmn_reystressmodel;

// COMMON /rigidbody/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonRigidbody {
    int32_t irigb;
    int32_t irbtrim;
};
extern CommonRigidbody cmn_rigidbody;

// COMMON /ron/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonRon {
    float titleron[20];  // fortran titleron(20) — 1-based
};
extern CommonRon cmn_ron;

// COMMON /ronfiles/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonRonfiles {
    char rout[80];  // character*80
};
extern CommonRonfiles cmn_ronfiles;

// COMMON /sa_options/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonSaOptions {
    int32_t i_saneg;
    int32_t i_sanoft2;
    float sa_cw2;
    float sa_cw3;
    float sa_cv1;
    float sa_ct3;
    float sa_ct4;
    float sa_cb1;
    float sa_cb2;
    float sa_sigma;
    float sa_karman;
};
extern CommonSaOptions cmn_sa_options;

// COMMON /segment/ — unique, 4 declaration site(s) in 4 file(s)
struct CommonSegment {
    int32_t nsgtop;
};
extern CommonSegment cmn_segment;

// COMMON /singular/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonSingular {
    float atol;
};
extern CommonSingular cmn_singular;

// COMMON /sminn/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonSminn {
    int32_t isminc;
    int32_t ismincforce;
};
extern CommonSminn cmn_sminn;

// COMMON /sourceterm/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonSourceterm {
    float xdir_only_source;
};
extern CommonSourceterm cmn_sourceterm;

// COMMON /specialtop_kmax1001/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonSpecialtopKmax1001 {
    int32_t i_specialtop_kmax1001;
    float a_specialtop_kmax1001;
    float xc_specialtop_kmax1001;
    float sig_specialtop_kmax1001;
    float vtp_specialtop_kmax1001;
    float wc_specialtop_kmax1001;
    float fac_specialtop_kmax1001;
    float cc_specialtop_kmax1001;
    float xerf_specialtop_kmax1001;
    float sigerf_specialtop_kmax1001;
};
extern CommonSpecialtopKmax1001 cmn_specialtop_kmax1001;

// COMMON /titles/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonTitles {
    char title1[80];  // character*80
    char title2[80];  // character*80
    char title3[80];  // character*80
};
extern CommonTitles cmn_titles;

// COMMON /trim/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonTrim {
    float dmtrmn;
    float dmtrmnm;
    float dlcln;
    float dlclnm;
    float trtol;
    float cmy;
    float cnw;
    float alf0;
    float alf1;
    float dzdt;
    float thtd0;
    float thtd1;
    float zrg0;
    float zrg1;
    float dtrmsmx;
    float dtrmsmn;
    float dalfmx;
    float ddtmx;
    float ddtrm0;
    float ddtrm1;
    int32_t itrmt;
    int32_t itrminc;
    float fp[16];  // fortran fp(4,4) column-major, wrap with FortranArray2DRef
    float tp[16];  // fortran tp(4,4) column-major, wrap with FortranArray2DRef
    float zlfct;
    float epstr;
    float relax;
    int32_t ittrst;
};
extern CommonTrim cmn_trim;

// COMMON /turbconv/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonTurbconv {
    float cflturb[7];  // fortran cflturb(7) — 1-based
    float edvislim;
    int32_t iturbprod;
    int32_t nsubturb;
    int32_t nfreeze;
    int32_t iwarneddy;
    int32_t itime2read;
    int32_t itaturb;
    float tur1cut;
    float tur2cut;
    int32_t iturbord;
    float tur1cutlev;
    float tur2cutlev;
};
extern CommonTurbconv cmn_turbconv;

// COMMON /unit5/ — unique, 6 declaration site(s) in 6 file(s)
struct CommonUnit5 {
    int32_t iunit5;
};
extern CommonUnit5 cmn_unit5;

// COMMON /unst/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonUnst {
    float time;
    float cfltau;
    int32_t ntstep;
    int32_t ita;
    int32_t iunst;
    float cfltau0;
    float cfltaumax;
};
extern CommonUnst cmn_unst;

// COMMON /wallvel_2034/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonWallvel2034 {
    float uub_2034;
    float vvb_2034;
    float wwb_2034;
    float vvb_xaxisrot2034;
};
extern CommonWallvel2034 cmn_wallvel_2034;

// COMMON /writestuff/ — unique, 1 declaration site(s) in 1 file(s)
struct CommonWritestuff {
    int32_t ifort50write;
    int32_t j_ifort50write;
    int32_t i_ifort50write;
};
extern CommonWritestuff cmn_writestuff;

// COMMON /zero/ — unique, 2 declaration site(s) in 2 file(s)
struct CommonZero {
    int32_t iexp;
};
extern CommonZero cmn_zero;
