// SPDX-License-Identifier: Apache-2.0
// Copyright 2001 United States Government as represented by the
// Administrator of the National Aeronautics and Space Administration.
// Copyright 2026 Jason Huang and cfl3d-cpp contributors (C++ translation).
// Licensed under the Apache License, Version 2.0 (see the LICENSE file).
//
// common_blocks.cpp — auto-generated by f2cpp common_mapper.
// Single definition of every COMMON block instance.
#include "common_blocks.h"

CommonAlphait cmn_alphait = {};
CommonAvgdata cmn_avgdata = {};
CommonAxisym cmn_axisym = {};
CommonBin cmn_bin = {};
CommonBlock cmn_block = {};
CommonCflfiles cmn_cflfiles = {};
CommonCgns cmn_cgns = {};
CommonChk1 cmn_chk1 = {};
CommonComplx cmn_complx = {};
CommonConstit cmn_constit = {};
CommonCurvat cmn_curvat = {};
CommonDeformz cmn_deformz = {};
CommonDes cmn_des = {};
CommonEasmlim cmn_easmlim = {};
CommonEasmv cmn_easmv = {};
CommonElasticSs cmn_elastic_ss = {};
CommonEntfix cmn_entfix = {};
CommonFilenam2 cmn_filenam2 = {};
CommonFluid cmn_fluid = {};
CommonFluid2 cmn_fluid2 = {};
CommonFullns cmn_fullns = {};
CommonGhost cmn_ghost = {};
CommonGinfo2 cmn_ginfo2 = {};
CommonGrdinfo cmn_grdinfo = {};
CommonGridtrans cmn_gridtrans = {};
CommonInfo cmn_info = {};
CommonInfo2 cmn_info2 = {};
CommonInfo3 cmn_info3 = {};
CommonInitfac cmn_initfac = {};
CommonIsBlockbc cmn_is_blockbc = {};
CommonIsPatch cmn_is_patch = {};
CommonIupdate cmn_iupdate = {};
CommonIvals cmn_ivals = {};
CommonKey cmn_key = {};
CommonKonew cmn_konew = {};
CommonLam cmn_lam = {};
CommonLesinfo cmn_lesinfo = {};
CommonMaxiv cmn_maxiv = {};
CommonMemory cmn_memory = {};
CommonMemry cmn_memry = {};
CommonMgv cmn_mgv = {};
CommonMms cmn_mms = {};
CommonMoov cmn_moov = {};
CommonMydist2 cmn_mydist2 = {};
CommonNoninertial cmn_noninertial = {};
CommonOldbl cmn_oldbl = {};
CommonPlot3dtyp cmn_plot3dtyp = {};
CommonPrecon1 cmn_precon1 = {};
CommonPrecond cmn_precond = {};
CommonRandomInput cmn_random_input = {};
CommonRbstmt2 cmn_rbstmt2 = {};
CommonReystressmodel cmn_reystressmodel = {};
CommonRigidbody cmn_rigidbody = {};
CommonRon cmn_ron = {};
CommonRonfiles cmn_ronfiles = {};
CommonSaOptions cmn_sa_options = {};
CommonSegment cmn_segment = {};
CommonSingular cmn_singular = {};
CommonSminn cmn_sminn = {};
CommonSourceterm cmn_sourceterm = {};
CommonSpecialtopKmax1001 cmn_specialtop_kmax1001 = {};
CommonTitles cmn_titles = {};
CommonTrim cmn_trim = {};
CommonTurbconv cmn_turbconv = {};
CommonUnit5 cmn_unit5 = {};
CommonUnst cmn_unst = {};
CommonWallvel2034 cmn_wallvel_2034 = {};
CommonWritestuff cmn_writestuff = {};
CommonZero cmn_zero = {};
