// SPDX-License-Identifier: Apache-2.0
// Copyright 2001 United States Government as represented by the
// Administrator of the National Aeronautics and Space Administration.
// Copyright 2026 Jason Huang and cfl3d-cpp contributors (C++ translation).
// Licensed under the Apache License, Version 2.0 (see the LICENSE file).
//
// This file is part of cfl3d-cpp, a C++ translation (MODIFIED) of NASA CFL3D
// (https://github.com/nasa/CFL3D). Independent, unofficial; not endorsed by
// or affiliated with NASA.
#pragma once
#include "runtime/fortran_array.h"
#include "runtime/common_blocks.h"
#include <complex>
#include <cstdint>

namespace bc_info_ns {

void bc(int& ntime, int& nbl, FortranArray2DRef<int> lw, FortranArray2DRef<int> lw2, FortranArray1DRef<double> w, int& mgwk, FortranArray1DRef<double> wk, int& nwork, double& cl, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& maxbl, int& maxgr, int& maxseg, FortranArray1DRef<int> itrans, FortranArray1DRef<int> irotat, FortranArray1DRef<int> idefrm, FortranArray1DRef<int> igridg, FortranArray1DRef<int> nblg, FortranArray1DRef<int> nbci0, FortranArray1DRef<int> nbcj0, FortranArray1DRef<int> nbck0, FortranArray1DRef<int> nbcidim, FortranArray1DRef<int> nbcjdim, FortranArray1DRef<int> nbckdim, FortranArray4DRef<int> ibcinfo, FortranArray4DRef<int> jbcinfo, FortranArray4DRef<int> kbcinfo, FortranArray3DRef<int> bcfilei, FortranArray3DRef<int> bcfilej, FortranArray3DRef<int> bcfilek, FortranArray3DRef<int> lwdat, int& myid, FortranArray1DRef<int> idimg, FortranArray1DRef<int> jdimg, FortranArray1DRef<int> kdimg, FortranArray1DRef<char[80]> bcfiles, int& mxbcfil, int& nummem);
void bc_info(int& ntime, int& nbl, FortranArray1DRef<double> w, int& mgwk, FortranArray4DRef<int> ibcinfo, FortranArray4DRef<int> jbcinfo, FortranArray4DRef<int> kbcinfo, FortranArray1DRef<int> nbci0, FortranArray1DRef<int> nbcj0, FortranArray1DRef<int> nbck0, FortranArray1DRef<int> nbcidim, FortranArray1DRef<int> nbcjdim, FortranArray1DRef<int> nbckdim, FortranArray3DRef<int> bcfilei, FortranArray3DRef<int> bcfilej, FortranArray3DRef<int> bcfilek, FortranArray1DRef<int> igridg, FortranArray1DRef<int> itrans, FortranArray1DRef<int> irotat, FortranArray1DRef<int> idefrm, FortranArray1DRef<int> idimg, FortranArray1DRef<int> jdimg, FortranArray1DRef<int> kdimg, FortranArray1DRef<int> nblg, FortranArray1DRef<int> iibg, FortranArray1DRef<int> kkbg, FortranArray1DRef<int> jjbg, FortranArray1DRef<int> ibcg, FortranArray2DRef<int> ibpntsg, FortranArray1DRef<int> iipntsg, FortranArray1DRef<int> lig, FortranArray1DRef<int> lbg, FortranArray2DRef<int> isav_blk, FortranArray2DRef<int> isav_prd, FortranArray1DRef<int> iemg, int& nbli, FortranArray1DRef<double> geom_miss, FortranArray1DRef<double> period_miss, int& ninter, FortranArray2DRef<int> iindex, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& myid, FortranArray1DRef<int> mblk2nd, int& ibufdim, int& maxbl, int& maxseg, int& iitot, int& intmax, int& nsub1, int& mxbli, int& lbcprd, double& epsc0, double& epsrot, FortranArray3DRef<int> lwdat, int& maxgr, FortranArray1DRef<int> iovrlp, FortranArray1DRef<char[80]> bcfiles, int& mxbcfil);
void out1000(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim);
void out1001(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim);
void out1002(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim);
void out1003(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& myid);
void out1005(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& inormmom);
void out1008(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim);
void out1011(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim);
void out1012(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim);
void out1013(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim);
void out2002(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& mdim, int& ndim, FortranArray4DRef<double> bcdata, char (&filname)[80], int& myid, FortranArray1DRef<int> mblk2nd, int& maxbl);
void out2003(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& mdim, int& ndim, FortranArray4DRef<double> bcdata, char (&filname)[80], int& myid, FortranArray1DRef<int> mblk2nd, int& maxbl);
void out2004(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& mdim, int& ndim, FortranArray4DRef<double> bcdata, char (&filname)[80], int& myid, FortranArray1DRef<int> mblk2nd, int& maxbl, int& iout);
void out2005(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& mdim, int& ndim, FortranArray4DRef<double> bcdata, int& nbl, int& jdimp, int& kdimp, int& idimp, int& nblp, char (&filname)[80], int& myid, FortranArray1DRef<int> mblk2nd, int& maxbl);
void out2006(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& mdim, int& ndim, FortranArray4DRef<double> bcdata, char (&filname)[80], int& nblc, int& myid, FortranArray1DRef<int> mblk2nd, int& maxbl);
void out2007(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& mdim, int& ndim, FortranArray4DRef<double> bcdata, char (&filname)[80], int& myid, FortranArray1DRef<int> mblk2nd, int& maxbl);
void out2008(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& mdim, int& ndim, FortranArray4DRef<double> bcdata, char (&filname)[80], int& myid, FortranArray1DRef<int> mblk2nd, int& maxbl, int& iout);
void out2009(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& mdim, int& ndim, FortranArray4DRef<double> bcdata, char (&filname)[80], int& myid, FortranArray1DRef<int> mblk2nd, int& maxbl, int& iflgg);
void out2019(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& mdim, int& ndim, FortranArray4DRef<double> bcdata, char (&filname)[80], int& myid, FortranArray1DRef<int> mblk2nd, int& maxbl);
void out2016(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& mdim, int& ndim, FortranArray4DRef<double> bcdata, char (&filname)[80], int& myid, FortranArray1DRef<int> mblk2nd, int& maxbl, int& iout);
void out2026(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& mdim, int& ndim, FortranArray4DRef<double> bcdata, char (&filname)[80], int& myid, FortranArray1DRef<int> mblk2nd, int& maxbl);
void out2102(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& mdim, int& ndim, FortranArray4DRef<double> bcdata, char (&filname)[80], int& myid, FortranArray1DRef<int> mblk2nd, int& maxbl, int& iflag);
void out9999(int& jdim, int& kdim, int& idim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& nface, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim);

} // namespace bc_info_ns
