// SPDX-License-Identifier: Apache-2.0
// Copyright 2001 United States Government as represented by the
// Administrator of the National Aeronautics and Space Administration.
// Copyright 2026 Jason Huang and cfl3d-cpp contributors (C++ translation).
// Licensed under the Apache License, Version 2.0 (see the LICENSE file).
//
// This file is part of cfl3d-cpp, a C++ translation (MODIFIED) of NASA CFL3D
// (https://github.com/nasa/CFL3D). Independent, unofficial; not endorsed by
// or affiliated with NASA.
#pragma once
#include "runtime/fortran_array.h"
#include "runtime/common_blocks.h"
#include <complex>
#include <cstdint>

namespace updatedg_ns {

void cellvol(int& jdim, int& kdim, int& idim, FortranArray3DRef<double> x, FortranArray3DRef<double> y, FortranArray3DRef<double> z, FortranArray3DRef<double> sj, FortranArray3DRef<double> sk, FortranArray3DRef<double> si, FortranArray3DRef<double> vol, FortranArray2DRef<double> t, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& myid, FortranArray1DRef<int> mblk2nd, int& maxbl, int& nbl, int& iflagv1, int& iflagv, int& imin, int& imax, int& jmin, int& jmax, int& kmin, int& kmax);
void metric(int& jdim, int& kdim, int& idim, FortranArray3DRef<double> x, FortranArray3DRef<double> y, FortranArray3DRef<double> z, FortranArray3DRef<double> sj, FortranArray3DRef<double> sk, FortranArray3DRef<double> si, FortranArray2DRef<double> t, FortranArray3DRef<double> t1, int& nbl, int& iflag, int& icnt, FortranArray1DRef<int> nbci0, FortranArray1DRef<int> nbcj0, FortranArray1DRef<int> nbck0, FortranArray1DRef<int> nbcidim, FortranArray1DRef<int> nbcjdim, FortranArray1DRef<int> nbckdim, FortranArray4DRef<int> ibcinfo, FortranArray4DRef<int> jbcinfo, FortranArray4DRef<int> kbcinfo, int& maxbl, int& maxseg, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& myid, FortranArray1DRef<int> mblk2nd);
void update(int& jdim, int& kdim, int& idim, FortranArray4DRef<double> q, FortranArray2DRef<double> qj0, FortranArray2DRef<double> qk0, FortranArray2DRef<double> qi0, FortranArray2DRef<double> sj, FortranArray2DRef<double> sk, FortranArray2DRef<double> si, FortranArray1DRef<double> vol, FortranArray1DRef<double> dtj, FortranArray3DRef<double> vist3d, FortranArray3DRef<double> blank, FortranArray1DRef<double> x, FortranArray1DRef<double> y, FortranArray1DRef<double> z, FortranArray4DRef<double> res, FortranArray1DRef<double> wk0, FortranArray3DRef<double> vmuk, FortranArray3DRef<double> vmuj, FortranArray3DRef<double> vmui, FortranArray1DRef<double> wk, int& nwork, int& nbl, int& iover, FortranArray4DRef<double> vk0, FortranArray3DRef<double> bcj, FortranArray3DRef<double> bck, FortranArray3DRef<double> bci, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& myid, FortranArray1DRef<int> mblk2nd, int& maxbl, FortranArray3DRef<double> volk0, FortranArray4DRef<double> tursav, FortranArray4DRef<double> tk0, FortranArray3DRef<double> cmuv, FortranArray1DRef<int> iadvance, int& nummem, FortranArray4DRef<double> ux);
void updatedg(FortranArray2DRef<int> lw, FortranArray2DRef<int> lw2, FortranArray1DRef<double> w, int& mgwk, FortranArray1DRef<double> wk, int& nwork, int& iupdat, int& iseqr, int& maxbl, int& maxgr, int& maxseg, FortranArray1DRef<int> nbci0, FortranArray1DRef<int> nbcj0, FortranArray1DRef<int> nbck0, FortranArray1DRef<int> nbcidim, FortranArray1DRef<int> nbcjdim, FortranArray1DRef<int> nbckdim, FortranArray4DRef<int> ibcinfo, FortranArray4DRef<int> jbcinfo, FortranArray4DRef<int> kbcinfo, int& nblock, FortranArray1DRef<int> levelg, FortranArray1DRef<int> igridg, FortranArray1DRef<int> idefrm, FortranArray1DRef<int> ncgg, FortranArray1DRef<int> iadvance, FortranArray1DRef<int> nou, FortranArray2DRef<char[120]> bou, int& nbuf, int& ibufdim, int& myid, int& myhost, int& mycomm, FortranArray1DRef<int> mblk2nd, FortranArray2DRef<double> utrnsae, FortranArray2DRef<double> vtrnsae, FortranArray2DRef<double> wtrnsae, FortranArray2DRef<double> omgxae, FortranArray2DRef<double> omgyae, FortranArray2DRef<double> omgzae, FortranArray2DRef<double> xorgae, FortranArray2DRef<double> yorgae, FortranArray2DRef<double> zorgae, FortranArray2DRef<double> thtxae, FortranArray2DRef<double> thtyae, FortranArray2DRef<double> thtzae, FortranArray2DRef<double> rfrqtae, FortranArray2DRef<double> rfrqrae, FortranArray2DRef<int> icsi, FortranArray2DRef<int> icsf, FortranArray2DRef<int> jcsi, FortranArray2DRef<int> jcsf, FortranArray2DRef<int> kcsi, FortranArray2DRef<int> kcsf, FortranArray2DRef<double> freq, FortranArray2DRef<double> gmass, FortranArray2DRef<double> damp, FortranArray2DRef<double> x0, FortranArray2DRef<double> gf0, int& nmds, int& maxaes, FortranArray2DRef<double> aesrfdat, FortranArray3DRef<double> perturb, FortranArray1DRef<int> itrans, FortranArray1DRef<int> irotat, FortranArray3DRef<int> islavept, int& nslave, FortranArray2DRef<int> iskip, FortranArray2DRef<int> jskip, FortranArray2DRef<int> kskip, FortranArray2DRef<double> xs, FortranArray2DRef<double> xxn, FortranArray1DRef<int> nsegdfrm, FortranArray2DRef<int> idfrmseg, FortranArray2DRef<int> iaesurf, int& maxsegdg, FortranArray1DRef<int> iwk, int& nmaster, int& nt, FortranArray1DRef<double> xorig, FortranArray1DRef<double> yorig, FortranArray1DRef<double> zorig, FortranArray2DRef<double> xorgae0, FortranArray2DRef<double> yorgae0, FortranArray2DRef<double> zorgae0, FortranArray2DRef<int> icouple, FortranArray1DRef<int> ireq, int& nnodes, FortranArray2DRef<int> nblelst, FortranArray1DRef<int> iskmax, FortranArray1DRef<int> jskmax, FortranArray1DRef<int> kskmax, FortranArray1DRef<double> ue);
void elglobfe(FortranArray1DRef<double> sa, FortranArray1DRef<double> xst, FortranArray1DRef<double> yst, FortranArray1DRef<double> zst, FortranArray1DRef<double> xix, FortranArray1DRef<double> xiy, FortranArray1DRef<double> xiz, FortranArray1DRef<double> etax, FortranArray1DRef<double> etay, FortranArray1DRef<double> etaz, FortranArray1DRef<double> zetax, FortranArray1DRef<double> zetay, FortranArray1DRef<double> zetaz, FortranArray1DRef<double> ei, FortranArray1DRef<double> ej, FortranArray1DRef<double> ek, FortranArray1DRef<double> gij, FortranArray1DRef<double> gjk, FortranArray1DRef<double> gik, FortranArray1DRef<double> ooj, double& eps, FortranArray2DRef<double> stiffl, FortranArray3DRef<int> islavept, FortranArray1DRef<int> ija, int& nslave, int& nmaster, int& nnodes, int& myhost, int& myid, int& mycomm, FortranArray1DRef<int> mblk2nd, FortranArray2DRef<int> nblelst, int& maxbl, int& iseqr);
void s_gwrite(int& nbl, int& idim, int& jdim, int& kdim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& idim1, int& jdim1, int& kdim1, FortranArray3DRef<double> x, FortranArray3DRef<double> y, FortranArray3DRef<double> z);
void s_gread(int& nbl, int& idim, int& jdim, int& kdim, int& ista, int& iend, int& jsta, int& jend, int& ksta, int& kend, int& idim1, int& jdim1, int& kdim1, FortranArray3DRef<double> x, FortranArray3DRef<double> y, FortranArray3DRef<double> z);
void gridgen_glyf1(int& nbl);
void gridgen_glyf2(int& nbl);

} // namespace updatedg_ns
